//! Construct-kind catalog — the registry of what each language parser emits
//! for the Educator. Drives the `nao construct-kinds <lang>` markdown
//! generation that authors read when writing new rules.
//!
//! Per ADR-0001 each parser owns its own registry. The structures here are
//! only the shape; the data lives in the language-specific module
//! (`src/educator/java.rs`, …).

use std::fmt::Write;

/// One construct-kind a parser emits.
pub struct ConstructKindSpec {
    pub kind: &'static str,
    pub description: &'static str,
    pub attributes: &'static [AttributeSpec],
}

/// One attribute on a construct-kind. The `values` slot is informational —
/// authors read it to know what they can match against. The runtime evaluator
/// does not enforce it; EDU-004's validator does (when checking `match:` keys).
pub struct AttributeSpec {
    pub name: &'static str,
    pub description: &'static str,
    pub values: AttributeValues,
}

pub enum AttributeValues {
    /// Closed enumeration. The values are the legitimate match targets.
    Enum(&'static [&'static str]),
    /// Free-form identifier text (e.g. a method name, a variable name).
    Identifier,
    /// Free-form source text (e.g. the literal text of an expression).
    Text,
    /// Boolean attribute (the attribute is stringified as `"true"` or `"false"`).
    Boolean,
}

impl AttributeValues {
    fn describe(&self) -> String {
        match self {
            AttributeValues::Enum(vals) => vals
                .iter()
                .map(|v| format!("`{}`", v))
                .collect::<Vec<_>>()
                .join(", "),
            AttributeValues::Identifier => "identifier text".to_string(),
            AttributeValues::Text => "source text".to_string(),
            AttributeValues::Boolean => "`true`, `false`".to_string(),
        }
    }
}

/// Render a per-language catalog to the canonical markdown shape. Output is
/// deterministic — same registry produces same bytes.
pub fn render_catalog(language: &str, specs: &[ConstructKindSpec]) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "# {} construct-kinds\n",
        capitalize(language)
    );
    let _ = writeln!(
        out,
        "_Generated by `nao construct-kinds {}` — do not edit by hand._\n",
        language
    );
    let _ = writeln!(
        out,
        "This file lists every construct-kind the {} parser emits for the Educator, with the attribute map each kind carries. Rule authors `applies-to:` one or more of these kinds and `match:` against the attributes below.\n",
        language
    );
    for spec in specs {
        let _ = writeln!(out, "## `{}`\n", spec.kind);
        let _ = writeln!(out, "{}\n", spec.description);
        if spec.attributes.is_empty() {
            let _ = writeln!(out, "_No attributes._\n");
            continue;
        }
        let _ = writeln!(out, "| Attribute | Values | Description |");
        let _ = writeln!(out, "|-----------|--------|-------------|");
        for attr in spec.attributes {
            let _ = writeln!(
                out,
                "| `{}` | {} | {} |",
                attr.name,
                attr.values.describe(),
                attr.description,
            );
        }
        let _ = writeln!(out);
    }
    out
}

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_uppercase().chain(chars).collect(),
        None => String::new(),
    }
}

/// Look up a spec by its construct-kind string. Linear scan — registries are tiny.
pub fn find<'a>(specs: &'a [ConstructKindSpec], kind: &str) -> Option<&'a ConstructKindSpec> {
    specs.iter().find(|s| s.kind == kind)
}

/// Resolve a language name to its registry. Adding a language means extending
/// this function — that explicit step is the seam ADR-0001 wants language
/// parsers to keep, rather than registering via a global trait or inventory.
pub fn for_language(language: &str) -> Option<&'static [ConstructKindSpec]> {
    match language {
        "java" => Some(super::java::JAVA_CONSTRUCT_KINDS),
        _ => None,
    }
}
