//! Per-language content index — renders `content/<lang>/INDEX.md` listing
//! every rule and lesson in the corpus grouped by construct-kind.
//!
//! Purpose: discoverability. As the corpus grows, agents (and humans) writing
//! a new rule or lesson need a fast way to check "what already attaches to
//! this construct-kind?" Browsing every file in `rules/` and `lessons/`
//! doesn't scale. The auto-generated index gives one stop.
//!
//! Source of truth = the rule and lesson files themselves (their
//! frontmatter). The renderer reads via the loaded [`Educator`] state. A
//! catalog-pin test keeps the on-disk file in sync with the renderer.

use std::collections::BTreeMap;
use std::fmt::Write;
use std::path::Path;

use super::corpus::Educator;
use super::lessons::Lesson;
use super::rules::Rule;

/// Render the full index markdown for a language. Deterministic — same
/// corpus produces the same bytes.
pub fn render_index(educator: &Educator, language: &str) -> String {
    let mut by_kind: BTreeMap<String, (Vec<&Rule>, Vec<&Lesson>)> = BTreeMap::new();

    for rule in educator.rules() {
        if rule.language != language {
            continue;
        }
        for kind in &rule.applies_to {
            by_kind.entry(kind.clone()).or_default().0.push(rule);
        }
    }
    for lesson in educator.lessons() {
        if lesson.language != language {
            continue;
        }
        for kind in &lesson.applies_to {
            by_kind.entry(kind.clone()).or_default().1.push(lesson);
        }
    }

    // Stable order inside each kind: by id.
    for (rules, lessons) in by_kind.values_mut() {
        rules.sort_by(|a, b| a.id.cmp(&b.id));
        lessons.sort_by(|a, b| a.id.cmp(&b.id));
    }

    let total_rules = educator
        .rules()
        .iter()
        .filter(|r| r.language == language)
        .count();
    let total_lessons = educator
        .lessons()
        .iter()
        .filter(|l| l.language == language)
        .count();

    let mut out = String::new();
    let _ = writeln!(out, "# {} Educator content — index\n", capitalize(language));
    let _ = writeln!(
        out,
        "_Generated by `nao educator-index {}` — do not edit by hand._\n",
        language
    );
    let _ = writeln!(
        out,
        "Every rule and lesson currently shipped for {}, grouped by the construct-kind it attaches to. Use this when authoring new content: skim the entries under the construct you plan to target — if something close already exists, extend it rather than ship a near-duplicate.\n",
        language
    );
    let _ = writeln!(
        out,
        "**Totals**: {} rule(s) · {} lesson(s) · {} construct-kind(s) covered.\n",
        total_rules,
        total_lessons,
        by_kind.len()
    );
    let _ = writeln!(out, "See also: [STYLE.md](STYLE.md) (rule voice), [construct-kinds.md](construct-kinds.md) (what the parser emits).\n");

    for (kind, (rules, lessons)) in &by_kind {
        let _ = writeln!(out, "## `{}`\n", kind);

        let _ = writeln!(out, "### Rules");
        if rules.is_empty() {
            let _ = writeln!(out, "\n_(none yet)_\n");
        } else {
            let _ = writeln!(out);
            let _ = writeln!(out, "| Id | Severity | Kind | Title |");
            let _ = writeln!(out, "|---|---|---|---|");
            for rule in rules {
                let link = relative_link(&rule.source_path);
                let _ = writeln!(
                    out,
                    "| [{}]({}) | {} | {} | {} |",
                    rule.id,
                    link,
                    rule.severity,
                    rule.kind,
                    rule.title()
                );
            }
            let _ = writeln!(out);
        }

        let _ = writeln!(out, "### Lessons");
        if lessons.is_empty() {
            let _ = writeln!(out, "\n_(none yet)_\n");
        } else {
            let _ = writeln!(out);
            let _ = writeln!(out, "| Id | Level | Title |");
            let _ = writeln!(out, "|---|---|---|");
            for lesson in lessons {
                let link = relative_link(&lesson.source_path);
                let _ = writeln!(
                    out,
                    "| [{}]({}) | {} | {} |",
                    lesson.id, link, lesson.level, lesson.title
                );
            }
            let _ = writeln!(out);
        }
    }
    out
}

/// Build the markdown link the INDEX.md (which lives at
/// `content/<lang>/INDEX.md`) uses to point at each rule / lesson file.
/// The link is the path from `rules/` or `lessons/` downward — so a flat file
/// at `content/java/rules/foo.md` renders as `rules/foo.md`, and a nested
/// file at `content/java/rules/control-flow/foo.md` renders as
/// `rules/control-flow/foo.md`.
fn relative_link(source_path: &Path) -> String {
    // Find the ancestor named `rules` or `lessons`; the link is everything from
    // that ancestor down. Falls back to the file name alone if neither is
    // found (only happens for paths constructed in tests).
    let components: Vec<&std::ffi::OsStr> =
        source_path.components().map(|c| c.as_os_str()).collect();
    let bucket_idx = components.iter().enumerate().rposition(|(_, c)| {
        let s = c.to_string_lossy();
        s == "rules" || s == "lessons"
    });
    match bucket_idx {
        Some(i) => components[i..]
            .iter()
            .map(|c| c.to_string_lossy())
            .collect::<Vec<_>>()
            .join("/"),
        None => source_path
            .file_name()
            .map(|n| n.to_string_lossy().into_owned())
            .unwrap_or_default(),
    }
}

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_uppercase().chain(chars).collect(),
        None => String::new(),
    }
}
