//! Kotlin stdlib / common method names filtered out during call extraction.

pub(super) fn is_stdlib_method(name: &str) -> bool {
    matches!(
        name,
        "toString"
            | "hashCode"
            | "equals"
            | "compareTo"
            | "println"
            | "print"
            | "require"
            | "check"
            | "error"
            | "let"
            | "run"
            | "with"
            | "apply"
            | "also"
            | "map"
            | "filter"
            | "forEach"
            | "flatMap"
            | "reduce"
            | "fold"
            | "any"
            | "all"
            | "none"
            | "count"
            | "first"
            | "last"
            | "find"
            | "firstOrNull"
            | "lastOrNull"
            | "toList"
            | "toSet"
            | "toMap"
            | "toMutableList"
            | "sortedBy"
            | "groupBy"
            | "associate"
            | "partition"
            | "get"
            | "set"
            | "add"
            | "remove"
            | "contains"
            | "size"
            | "isEmpty"
            | "isNotEmpty"
            | "clear"
            | "trim"
            | "lowercase"
            | "uppercase"
            | "replace"
            | "split"
            | "joinToString"
            | "substring"
            | "startsWith"
            | "endsWith"
            | "plus"
            | "minus"
            | "times"
            | "div"
            | "listOf"
            | "mapOf"
            | "setOf"
            | "arrayOf"
            | "mutableListOf"
            | "mutableMapOf"
            | "mutableSetOf"
            | "emptyList"
            | "emptyMap"
            | "emptySet"
    )
}
