//! Recognition of JavaScript / TypeScript built-ins and common DOM/Promise
//! method names. Used by the call-extraction pass to filter out calls that
//! aren't interesting for the visualizer.

pub(crate) fn is_stdlib_function(name: &str) -> bool {
    matches!(
        name,
        "toString"
            | "valueOf"
            | "hasOwnProperty"
            | "isPrototypeOf"
            | "propertyIsEnumerable"
            | "toLocaleString"
            | "console"
            | "log"
            | "warn"
            | "error"
            | "info"
            | "debug"
            | "parseInt"
            | "parseFloat"
            | "isNaN"
            | "isFinite"
            | "encodeURIComponent"
            | "decodeURIComponent"
            | "encodeURI"
            | "decodeURI"
            | "JSON"
            | "stringify"
            | "parse"
            | "keys"
            | "values"
            | "entries"
            | "assign"
            | "freeze"
            | "push"
            | "pop"
            | "shift"
            | "unshift"
            | "splice"
            | "slice"
            | "concat"
            | "join"
            | "indexOf"
            | "includes"
            | "find"
            | "findIndex"
            | "filter"
            | "map"
            | "reduce"
            | "forEach"
            | "some"
            | "every"
            | "sort"
            | "reverse"
            | "flat"
            | "flatMap"
            | "fill"
            | "from"
            | "of"
            | "trim"
            | "trimStart"
            | "trimEnd"
            | "split"
            | "replace"
            | "replaceAll"
            | "match"
            | "search"
            | "startsWith"
            | "endsWith"
            | "padStart"
            | "padEnd"
            | "repeat"
            | "toLowerCase"
            | "toUpperCase"
            | "charAt"
            | "charCodeAt"
            | "substring"
            | "then"
            | "catch"
            | "finally"
            | "resolve"
            | "reject"
            | "all"
            | "allSettled"
            | "race"
            | "any"
            | "setTimeout"
            | "setInterval"
            | "clearTimeout"
            | "clearInterval"
            | "addEventListener"
            | "removeEventListener"
            | "querySelector"
            | "querySelectorAll"
            | "getElementById"
            | "createElement"
            | "appendChild"
            | "removeChild"
            | "setAttribute"
            | "getAttribute"
            | "require"
    )
}
