//! Recognition of Java standard-library / common method names.
//!
//! Used by the call-extraction pass to filter out calls that aren't
//! interesting for the visualizer.

pub(crate) fn is_stdlib_method(name: &str) -> bool {
    matches!(
        name,
        "toString"
            | "hashCode"
            | "equals"
            | "clone"
            | "compareTo"
            | "valueOf"
            | "values"
            | "ordinal"
            | "name"
            | "get"
            | "set"
            | "add"
            | "remove"
            | "put"
            | "contains"
            | "containsKey"
            | "size"
            | "isEmpty"
            | "clear"
            | "iterator"
            | "hasNext"
            | "next"
            | "length"
            | "charAt"
            | "substring"
            | "trim"
            | "toLowerCase"
            | "toUpperCase"
            | "append"
            | "insert"
            | "delete"
            | "replace"
            | "println"
            | "print"
            | "printf"
            | "format"
            | "close"
            | "flush"
            | "read"
            | "write"
            | "getClass"
            | "notify"
            | "notifyAll"
            | "wait"
            | "stream"
            | "collect"
            | "map"
            | "filter"
            | "forEach"
            | "reduce"
            | "of"
            | "ofNullable"
            | "orElse"
            | "orElseGet"
            | "isPresent"
    )
}
